# Generated by Django 5.2 on 2025-05-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
