# Generated by Django 5.2 on 2026-08-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscription_plan',
        ),
    ]
