# Generated by Django 5.2 on 2026-08-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_unique_customuser_email_ci_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('username__contains', '@'), _negated=True), name='customuser_username_without_at'),
        ),
    ]
