# Generated by Django 5.2 on 2026-08-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_customuser_username_without_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone',
        ),
    ]
