# Generated by Django 5.2 on 2026-08-16 20:56

from django.db import migrations, models
from django.utils import timezone


def backfill_email_verified_at(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')

    CustomUser.objects.filter(
        is_active=True,
        email_verified_at__isnull=True,
    ).update(
        email_verified_at=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_teacher_bio_remove_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            backfill_email_verified_at,
            migrations.RunPython.noop,
        ),
    ]