# Generated by Django 5.2 on 2025-04-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='period',
            field=models.CharField(blank=True, choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=10),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='school',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
