# Generated by Django 5.2 on 2025-05-02 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_classgroup_period_classgroup_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='lessons_sets', to='core.exercise'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises_item', to='core.lesson'),
        ),
    ]
