# Generated by Django 5.2 on 2025-05-02 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_username'),
        ('core', '0003_alter_student_options_lesson_exercises_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['title'], 'verbose_name': 'Exercício', 'verbose_name_plural': 'Exercícios'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='lesson',
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='accounts.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Exercício modelo para reutilização'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='core.exercise'),
        ),
    ]
