# Generated by Django 5.2 on 2025-05-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_exercise_options_remove_exercise_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('lesson', 'Aula'), ('exercise', 'Exercício'), ('general', 'Geral')], default='general', max_length=10),
        ),
    ]
