# Generated by Django 5.2 on 2025-05-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#3B82F6', 'Azul'), ('#10B981', 'Verde'), ('#F59E0B', 'Amarelo'), ('#8B5CF6', 'Roxo'), ('#EC4899', 'Rosa'), ('#6366F1', 'Índigo'), ('#EF4444', 'Vermelho'), ('#14B8A6', 'Turquesa')], default='#3B82F6', max_length=7),
        ),
    ]
