# Generated by Django 5.2 on 2025-06-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgroup',
            options={'ordering': ['period', 'schedule', 'name']},
        ),
        migrations.AddField(
            model_name='classgroup',
            name='schedule',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Horário'),
        ),
    ]
