# Generated by Django 5.2 on 2026-07-28 22:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_student_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='year',
            field=models.IntegerField(default=core.models.current_year),
        ),
    ]
