# Generated by Django 5.2 on 2026-07-30 21:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_classgroup_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da turma'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='period',
            field=models.CharField(blank=True, choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=10, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='school',
            field=models.CharField(max_length=100, verbose_name='Escola'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='year',
            field=models.IntegerField(default=core.models.current_year, verbose_name='Ano letivo'),
        ),
    ]
