# Generated by Django 5.2 on 2026-07-30 21:18

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher_display_name'),
        ('core', '0010_alter_classgroup_description_alter_classgroup_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classgroup',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('school'), models.F('teacher'), models.F('year'), name='unique_class_group_teacher_name_school_year'),
        ),
    ]
