# Generated by Django 5.2 on 2026-07-30 21:41

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_classgroup_unique_class_group_teacher_name_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='year',
            field=models.IntegerField(default=core.models.current_year, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano letivo'),
        ),
    ]
