# Generated by Django 5.2 on 2026-08-01 22:07

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_classgroup_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='year',
            field=models.IntegerField(default=core.models.current_year, validators=[django.core.validators.MinValueValidator(2000, message='O ano letivo deve ser igual ou superior a 2000.'), django.core.validators.MaxValueValidator(2100, message='O ano letivo deve ser igual ou inferior a 2100.')], verbose_name='Ano letivo'),
        ),
    ]
