# Generated by Django 5.2 on 2026-08-02 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_classgroup_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='Modelo utilizado para gerar este exercício.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_exercises', to='core.exercise', verbose_name='Modelo de origem'),
        ),
    ]
