# Generated by Django 5.2 on 2026-08-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_exercise_source_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o exercício está disponível para uso.', verbose_name='Ativo'),
        ),
    ]
