# Generated by Django 5.2 on 2026-08-02 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_exercise_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duração estimada em minutos, entre 1 e 1440.', null=True, validators=[django.core.validators.MinValueValidator(1, message='A duração deve ser de pelo menos 1 minuto.'), django.core.validators.MaxValueValidator(1440, message='A duração não pode ultrapassar 1440 minutos.')], verbose_name='Duração'),
        ),
    ]
