# Generated by Django 5.2 on 2026-08-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_lessonexercise_alter_lesson_exercises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('planned', 'Planejada'), ('completed', 'Realizada'), ('cancelled', 'Cancelada')], default='planned', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(verbose_name='Data de aplicação'),
        ),
    ]
