# Generated by Django 5.2 on 2026-08-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_lesson_status_alter_lesson_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='objectives',
        ),
    ]
