# Generated by Django 5.2 on 2026-08-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_lesson_objectives'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningobjective',
            options={'ordering': ['title'], 'verbose_name': 'Objetivo de aprendizagem', 'verbose_name_plural': 'Objetivos de aprendizagem'},
        ),
        migrations.AlterField(
            model_name='learningobjective',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
