# Generated by Django 5.2 on 2026-08-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_learningobjective_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o objetivo está disponível para novas associações.', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se a tag está disponível para novas associações.', verbose_name='Ativa'),
        ),
    ]
