# Generated by Django 5.2 on 2026-08-06 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_tag_options_learningobjective_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningobjective',
            name='tags',
        ),
    ]
