# Generated by Django 5.2 on 2026-08-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_learningobjective_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FutureIdea',
        ),
    ]
