# Generated by Django 5.2 on 2026-08-07 22:55

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher_display_name'),
        ('core', '0023_delete_futureidea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='type',
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('teacher'), name='unique_tag_name_per_teacher'),
        ),
    ]
