# Generated by Django 5.2 on 2026-08-10 21:34

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher_display_name'),
        ('core', '0024_remove_tag_type_tag_unique_tag_name_per_teacher'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='learningobjective',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('teacher'), name='unique_learning_objective_title_per_teacher'),
        ),
    ]
